"""Storage backend for the gateway: sqlite (dev / single-node / air-gapped) or
PostgreSQL (production, multi-instance). One small adapter so keys / usage /
packs don't each grow a driver branch.

Backend is chosen by the connection string:
  - ``postgres://…`` / ``postgresql://…``  → PostgreSQL via ``psycopg`` (extra dep)
  - anything else                          → a sqlite file at that path

Set it once via ``DATABASE_URL`` (or ``KARST_GATEWAY_DATABASE_URL``), or pass a
path explicitly. The stores write sqlite-style ``?`` placeholders and portable
DDL; this layer translates both for Postgres.

Concurrency: sqlite keeps one connection (single-node, serialized). Postgres
opens a short-lived connection per operation, which is correct under concurrent
ASGI requests; wire ``psycopg_pool`` here if you need higher throughput.
"""
from __future__ import annotations

import os
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any


def resolve_url(explicit: str | Path | None = None) -> str:
    """``DATABASE_URL`` env wins (production); else the explicit sqlite path."""
    env = os.environ.get("KARST_GATEWAY_DATABASE_URL") or os.environ.get("DATABASE_URL")
    if env:
        return env
    if explicit is None:
        raise ValueError("no database configured: set DATABASE_URL or pass a path")
    return str(explicit)


def is_postgres(url: str) -> bool:
    return url.startswith(("postgres://", "postgresql://"))


@dataclass
class Result:
    """Materialised query result — rows are fetched eagerly so a Postgres
    connection can be returned to the pool / closed immediately."""

    rows: list[Any]
    rowcount: int
    lastid: int | None = None

    def one(self) -> Any | None:
        return self.rows[0] if self.rows else None

    def all(self) -> list[Any]:
        return self.rows


class Db:
    def __init__(self, url: str | Path) -> None:
        self.url = str(url)
        self.is_pg = is_postgres(self.url)
        self._conn = None
        if not self.is_pg:
            self._conn = sqlite3.connect(self.url)
            self._conn.row_factory = sqlite3.Row

    # -- translation ----------------------------------------------------------
    def _q(self, sql: str) -> str:
        # Stores use sqlite '?' placeholders; psycopg wants '%s'. No '?'
        # literals appear in our queries, so a plain swap is safe.
        return sql.replace("?", "%s") if self.is_pg else sql

    def _ddl(self, stmt: str) -> str:
        if not self.is_pg:
            return stmt
        return (
            stmt.replace(
                "INTEGER PRIMARY KEY AUTOINCREMENT",
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            ).replace(" REAL", " DOUBLE PRECISION")
        )

    # -- pg connection (short-lived, correct under concurrency) ---------------
    def _pg_connect(self):
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(self.url, autocommit=True, row_factory=dict_row)

    # -- api ------------------------------------------------------------------
    def executescript(self, schema: str) -> None:
        stmts = [s.strip() for s in schema.split(";") if s.strip()]
        if self.is_pg:
            with self._pg_connect() as conn:
                cur = conn.cursor()
                for s in stmts:
                    cur.execute(self._ddl(s))
            return
        for s in stmts:
            self._conn.execute(self._ddl(s))
        self._conn.commit()

    def run(self, sql: str, params: tuple | list = ()) -> Result:
        """Run a statement and return a materialised Result. Works for SELECT
        (rows populated) and INSERT/UPDATE/DELETE (rowcount populated)."""
        if self.is_pg:
            with self._pg_connect() as conn:
                cur = conn.cursor()
                cur.execute(self._q(sql), tuple(params))
                rows = cur.fetchall() if cur.description is not None else []
                return Result(rows=rows, rowcount=cur.rowcount)
        cur = self._conn.execute(sql, tuple(params))
        rows = cur.fetchall() if cur.description is not None else []
        self._conn.commit()
        return Result(rows=rows, rowcount=cur.rowcount)

    def insert(self, sql: str, params: tuple | list) -> int:
        """Run an INSERT and return the new row's id. The target table's primary
        key column must be named ``id`` (RETURNING on Postgres, lastrowid on sqlite)."""
        if self.is_pg:
            with self._pg_connect() as conn:
                cur = conn.cursor()
                cur.execute(self._q(sql) + " RETURNING id", tuple(params))
                return int(cur.fetchone()["id"])
        cur = self._conn.execute(sql, tuple(params))
        self._conn.commit()
        return int(cur.lastrowid)

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
